'use strict';
// No network or production writes: real helpers + extracted draft functions, mocked callable only.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const P=require(path.join(root,'ai-poster-ui.js'));
let count=0;
async function test(name,fn){await fn();count++;console.log('PASS '+name);}
const json=x=>JSON.parse(JSON.stringify(x));
function fixture(){return {ok:true,contractVersion:P.CONTRACT,schemaVersion:'bxh-arena.ai-create.v1',result:{schemaVersion:'bxh-arena.ai-create.v1',sourceMode:'poster-callable',timezone:'Asia/Taipei',activity:{name:'BXH 海報測試',date:'2026-10-10',locationName:'測試場地',address:'台南市測試路1號',registrationOpenAt:null,registrationCloseAt:null},events:[{key:'poster-1',name:'測試交流賽',date:'2026-10-10',checkInStart:'18:00',checkInEnd:null,startAt:'18:30',endAt:null,endDate:null,capacity:32,fee:250,targetGroup:null,formatType:'single',registrationEnabled:false,participantRestrictions:[]}],bundleOffers:[],warnings:[{code:'poster-review-required',severity:'warning',field:null,message:'請核對海報與獎品'}],posterText:'測試交流賽\n2026/10/10\n獎品：測試陀螺\n<script>alert(1)</script>'}};}
const toasts=[];let calls=0;
const ctx=vm.createContext({console,URL,Date,setTimeout,clearTimeout,JSON,document:{getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},window:{BxhPoster:P,engagementService:{aiCreatePosterParser:async()=>{calls++;return fixture();}}}});
vm.runInContext(`let state={id:'room1',meta:{},players:[],matches:[]};let firebaseUser={uid:'user1'},userProfile={role:'super_admin',active:true};let settingsFormDraft={name:'舊名稱',date:'2026-01-01',venueName:'舊店',venueAddress:'舊地址',location:'舊店｜舊地址',startTime:'17:00',formatType:'single',standardTemplate:{enabled:true,snapshot:{rules:'公版不可改'}}};let registrationFormDraft={eventDescription:'房主手動說明',registrationCapacity:99,registrationFee:999};let settingsFormDraftDirty=false,registrationFormDraftDirty=false;let aiCreateAssistantOpen=true,aiCreateSourceText='',aiCreateAssistantNotice='',aiCreateStructuredResult=null,aiCreateStructuredErrors=[],aiCreateSelectedEventKey='',aiCreateLastApplied=null,aiCreateReviewAcknowledged=false,aiCreateParseBusy=false,aiCreateSuggestionSelection={};const AI_CREATE_SCHEMA_VERSION='bxh-arena.ai-create.v1',AI_CREATE_TIMEZONE='Asia/Taipei',AI_CREATE_MAX_EVENTS=8,AI_CREATE_MAX_SOURCE_CHARS=12000;function render(){} function showToast(){} function ensureSettingsFormDraft(){} function ensureRegistrationFormDraft(){} function syncSettingsDraftFromDom(){} function syncRegistrationDraftFromDom(){} function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');} function epochToDatetimeLocal(){return '';} function openModal(){};`,ctx);
const names=['aiCreateBetaActorAllowed','validateAiCreateStructuredResult','aiCreateSelectedEvent','aiCreateIsoToEpoch','aiCreateHalfHourCompatible','aiCreateLocationText','normalizeGoogleMapsUrl','extractGoogleMapsUrlsFromText','aiCreateDraftMappingModel','applyAiCreateSelectedEventToDraft','aiCreateReviewReport','aiCreateReviewGate','runAiCreateParse'];
const helperStart=html.indexOf('// P7.13 poster input session'),helperEnd=html.indexOf('\nfunction aiCreateTimeMinusMinutes(',helperStart);
assert(helperStart>0&&helperEnd>helperStart);vm.runInContext(html.slice(helperStart,helperEnd),ctx);
for(const name of names){let start=html.indexOf('async function '+name+'(');if(start<0)start=html.indexOf('function '+name+'(');const end=html.indexOf('\n}',start)+2;assert(start>0&&end>start,name);vm.runInContext(html.slice(start,end),ctx,{filename:name+'.js'});}
const run=code=>vm.runInContext(code,ctx);
const api=run('({validateAiCreateStructuredResult,runAiCreateParse,aiCreateCaptureContext,aiCreateContextValid,aiCreateInvalidateInput,aiCreateReleasePoster,aiCreateDraftMappingModel,applyAiCreateSelectedEventToDraft,aiCreateReviewReport,aiCreateReviewGate,renderAiCreatePosterInput,renderAiCreatePosterEvidence})');
const image={name:'test.png',mimeType:'image/png',base64:'AAAA',width:100,height:100,byteLength:3,previewUrl:'blob:poster-local'};
ctx.testImage=image;
function ready(result=fixture().result){ctx.testResult=result;run('aiCreateAssistantOpen=true;userProfile.role="super_admin";firebaseUser.uid="user1";aiCreateSourceText="補充文案";aiCreatePosterFile=testImage;aiCreateStructuredResult=testResult;aiCreateSelectedEventKey=testResult.events[0].key;aiCreateParsedContext=aiCreateCaptureContext();aiCreateParseBusy=false;');}
(async()=>{
 await test('2048 px cap preserves aspect ratio',()=>assert.deepEqual(P.fitSize(4000,3000),{width:2048,height:1536}));
 for(const dims of [[63,100],[100,63],[100000,100000],[2048,64.5],[40000,64]])await test('Reject invalid dimension '+dims,()=>assert.throws(()=>P.fitSize(...dims)));
 await test('Reject unsupported file before decoding',()=>assert.rejects(P.prepareImage({type:'image/heic',size:100}),/poster-local-format/));
 await test('Reject oversized original before decoding',()=>assert.rejects(P.prepareImage({type:'image/png',size:P.MAX_FILE+1}),/poster-local-size/));
 await test('Exact backend request contract and payload allowlist',()=>{const r=P.buildRequest(image,'');assert.deepEqual(Object.keys(r).sort(),['contractVersion','poster','sourceText']);assert.deepEqual(Object.keys(r.poster).sort(),['base64','height','mimeType','width']);assert.equal(r.contractVersion,'bxh-arena.ai-poster.callable.v1');assert(!JSON.stringify(r).includes('previewUrl'));});
 await test('No truncation of overlong supplemental text',()=>assert.throws(()=>P.buildRequest(image,'x'.repeat(12001))));
 await test('Reject data URL masquerading as base64',()=>assert.throws(()=>P.buildRequest({...image,base64:'data:image/png;base64,AAAA'},'')));
 await test('Accept real deployed schema and preserve prize transcript',()=>{const r=P.validateEnvelope(fixture(),api.validateAiCreateStructuredResult);assert(r.posterText.includes('測試陀螺'));assert.equal(r.events[0].fee,250);});
 for(const key of ['ok','contractVersion','schemaVersion','result'])await test('Reject missing envelope '+key,()=>{const f=fixture();delete f[key];assert.throws(()=>P.validateEnvelope(f,api.validateAiCreateStructuredResult));});
 await test('Reject text endpoint response in poster route',()=>{const f=fixture();f.contractVersion='bxh-arena.ai-create.callable.v1';assert.throws(()=>P.validateEnvelope(f,api.validateAiCreateStructuredResult));});
 await test('Reject malformed warning and empty transcript',()=>{for(const m of [f=>f.result.warnings=[null],f=>f.result.posterText='',f=>f.result.posterText='x'.repeat(12001),f=>f.result.events[0].fee='250']){const f=fixture();m(f);assert.throws(()=>P.validateEnvelope(f,api.validateAiCreateStructuredResult));}});
 await test('Reject impossible calendar dates',()=>{const f=fixture();f.result.activity.date='2026-02-30';assert.throws(()=>P.validateEnvelope(f,api.validateAiCreateStructuredResult));assert(P.realDate('2024-02-29'));assert(!P.realDate('2026-02-29'));});
 await test('Ensure mandatory human review even when server omits warning',()=>{const f=fixture();f.result.warnings=[];assert(P.validateEnvelope(f,api.validateAiCreateStructuredResult).warnings.some(w=>w.code==='poster-review-required'));});
 await test('Source values do not mutate during validation',()=>{const f=fixture(),before=JSON.stringify(f),r=P.validateEnvelope(f,api.validateAiCreateStructuredResult);r.events[0].fee=1;assert.equal(JSON.stringify(f),before);});
 await test('Poster text and supplement remain separate in source evidence',()=>{const e=P.evidence(fixture().result,'人工補充');assert(e.includes('【海報辨識文字'));assert(e.includes('【房主補充文案】\n人工補充'));assert.equal(P.evidence(null,'  純文案  '),'純文案');});
 await test('Late response cannot survive replacement or input editing',()=>{ready();const c=api.aiCreateCaptureContext();assert(api.aiCreateContextValid(c));api.aiCreateInvalidateInput();assert(!api.aiCreateContextValid(c));});
 await test('Closing, room switching and account switching each invalidate context',()=>{for(const mutation of ['aiCreateAssistantOpen=false','state={...state,id:"new-room"}','firebaseUser.uid="other"','userProfile.role="player"','aiCreateSourceText="changed"','aiCreatePosterFile={...testImage}']){ready();const c=api.aiCreateCaptureContext();run(mutation);assert(!api.aiCreateContextValid(c),mutation);}});
 await test('Poster-only request reaches callable without requiring pasted text',async()=>{ready();run('aiCreateSourceText=""');await api.runAiCreateParse();assert.equal(calls,1);assert.equal(run('aiCreateStructuredResult.sourceMode'),'poster-callable');assert.equal(run('aiCreateParseBusy'),false);});
 await test('Original text-only parser still works with no selected image',async()=>{ready();run('aiCreatePosterFile=null;aiCreateSourceText="純文字活動";async function requestAiCreateStructuredResult(){return {ok:true,result:{...testResult,sourceMode:"remote-callable"},source:"remote-callable"}}');const before=calls;await api.runAiCreateParse();assert.equal(calls,before);assert.equal(run('aiCreateStructuredResult.sourceMode'),'remote-callable');assert.equal(run('aiCreateParseBusy'),false);});
 await test('Pending cancelled response is discarded and not applied',async()=>{let resolve;ctx.window.engagementService.aiCreatePosterParser=()=>new Promise(r=>resolve=r);ready();const promise=api.runAiCreateParse();api.aiCreateReleasePoster();run('aiCreateAssistantOpen=false');resolve(fixture());await promise;assert.equal(run('aiCreateStructuredResult'),null);assert.equal(run('aiCreateParseBusy'),false);});
 await test('Poster failure never falls back to text parser or modifies drafts',async()=>{ctx.window.engagementService.aiCreatePosterParser=async()=>{throw new Error('poster-disabled');};run('function requestAiCreateStructuredResult(){throw Error("MUST NOT FALL BACK")}');ready();const before=run('JSON.stringify([settingsFormDraft,registrationFormDraft,state])');await api.runAiCreateParse();assert.equal(run('JSON.stringify([settingsFormDraft,registrationFormDraft,state])'),before);assert.equal(run('aiCreateStructuredResult'),null);assert.match(run('aiCreateAssistantNotice'),/暫未開放/);});
 await test('Duplicate clicks while parser is busy send only once',async()=>{let resolve,n=0;ctx.window.engagementService.aiCreatePosterParser=()=>{n++;return new Promise(r=>resolve=r);};ready();const a=api.runAiCreateParse();await api.runAiCreateParse();assert.equal(n,1);resolve(fixture());await a;});
 await test('Apply changes only drafts, not live room state or public template',()=>{ready();const before=run('JSON.stringify(state)'),template=run('JSON.stringify(settingsFormDraft.standardTemplate)');const a=api.applyAiCreateSelectedEventToDraft();assert(a.ok);assert.equal(run('JSON.stringify(state)'),before);assert.equal(run('JSON.stringify(settingsFormDraft.standardTemplate)'),template);assert.equal(run('settingsFormDraft.startTime'),'18:30');assert.equal(run('registrationFormDraft.registrationFee'),250);assert.equal(run('registrationFormDraft.eventDescription'),'房主手動說明');});
 await test('Prize/source text fills an empty description only',()=>{ready();run('registrationFormDraft.eventDescription=""');assert(api.applyAiCreateSelectedEventToDraft().ok);assert.match(run('registrationFormDraft.eventDescription'),/測試陀螺/);});
 await test('Close/reset preview preserves applied poster warnings in Review Gate',()=>{ready();assert(api.applyAiCreateSelectedEventToDraft().ok);api.aiCreateReleasePoster();const report=api.aiCreateReviewReport();assert(report.warnings.some(w=>w.message.includes('核對海報')));assert.equal(api.aiCreateReviewGate(),false);});
 await test('Unknown server poster warnings remain visible through Review Gate',()=>{const f=fixture();f.result.warnings.push({code:'prize-unreadable',field:'posterText',severity:'warning',message:'獎品字樣模糊'});ready(f.result);api.applyAiCreateSelectedEventToDraft();api.aiCreateReleasePoster();assert(api.aiCreateReviewReport().warnings.some(w=>w.message==='獎品字樣模糊'));});
 await test('Date source conflict cannot fall back to activity date',()=>{const f=fixture();f.result.events[0].date=null;f.result.warnings.push({code:'source-conflict',field:'events[0].date',severity:'warning',message:'日期不一致'});ready(f.result);assert.equal(api.aiCreateDraftMappingModel().settings.date,'');assert(api.applyAiCreateSelectedEventToDraft().ok);assert.equal(run('settingsFormDraft.date'),'');assert(api.aiCreateReviewReport().blockers.some(w=>w.code==='date-missing'));});
 await test('Reapplying incomplete poster clears old AI scalar values, keeps manual description',()=>{const f=fixture();f.result.events[0].fee=null;f.result.events[0].capacity=null;f.result.events[0].startAt=null;ready(f.result);run('registrationFormDraft.eventDescription="手動保留"');assert(api.applyAiCreateSelectedEventToDraft().ok);assert.equal(run('registrationFormDraft.registrationFee'),null);assert.equal(run('registrationFormDraft.registrationCapacity'),null);assert.equal(run('settingsFormDraft.startTime'),'');assert.equal(run('registrationFormDraft.eventDescription'),'手動保留');});
 await test('Reject applying after source edit',()=>{ready();api.aiCreateInvalidateInput();assert.equal(api.applyAiCreateSelectedEventToDraft().ok,false);});
 await test('Inactive, test, frozen or deleted accounts cannot apply a result',()=>{for(const mutation of ['userProfile.active=false','userProfile.isTestAccount=true','userProfile.accountStatus="frozen"','userProfile.deleted=true']){ready();run(mutation);assert(!api.applyAiCreateSelectedEventToDraft().ok);run('userProfile={role:"super_admin",active:true}');}});
 await test('Do not apply into published rooms or rooms with players',()=>{for(const mutation of ['state.cloudCode="BXH-REAL"','state.players=[{id:"p"}]','state.startedAt=1']){ready();run(mutation);assert.equal(api.applyAiCreateSelectedEventToDraft().ok,false);run('delete state.cloudCode;state.players=[];delete state.startedAt');}});
 await test('Transcript and filename are escaped in UI',()=>{ready();const evidence=api.renderAiCreatePosterEvidence();assert(!evidence.includes('<script>'));assert(evidence.includes('&lt;script&gt;'));run('aiCreatePosterFile={...testImage,name:"<img src=x onerror=alert(1)>"}');assert(!api.renderAiCreatePosterInput().includes('<img src=x'));});
 await test('No persistence, direct room write or secret access in image module',()=>{const source=fs.readFileSync(path.join(root,'ai-poster-ui.js'),'utf8');assert(!/localStorage|sessionStorage|indexedDB|setDoc|updateDoc|writeBatch|apiKey|process\.env|console\.log/.test(source));});
 await test('Cover uploads only for the same room and actor after publication',async()=>{
   const start=html.indexOf('async function publishPendingPosterCover('),end=html.indexOf('\n}',start)+2;
   assert(start>0&&end>start);
   vm.runInContext('let publicTournamentsCache=[];',ctx);
   vm.runInContext(html.slice(start,end),ctx);
   let uploads=0;
   ctx.window.engagementService.roomPosterCover=async()=>{uploads++;return {ok:true};};
   run('aiCreateCoverPending={roomId:"old-room",uid:"user1",cover:{base64:"only-in-memory"}}');
   await run('publishPendingPosterCover("BXH-ABC123")');assert.equal(uploads,0);
   run('aiCreateCoverPending.roomId=state.id;aiCreateCoverPending.uid="other"');
   await run('publishPendingPosterCover("BXH-ABC123")');assert.equal(uploads,0);
   run('aiCreateCoverPending.uid="user1"');
   await run('publishPendingPosterCover("BXH-ABC123")');assert.equal(uploads,1);
   assert.equal(run('aiCreateCoverPending'),null);
 });
 await test('Callable bridge keeps original text endpoint and separate poster timeout',()=>{assert(html.includes('async aiCreateParser(payload){return callEngagementFunction("parseTournamentAnnouncementV1",payload,45000);}'));assert(html.includes('async aiCreatePosterParser(payload){return callEngagementFunction("parseTournamentPosterV1",payload,60000);}'));assert(html.includes('套用 BXH 賽事公版'));});
 console.log('P7.13 regression cases passed: '+count);
})().catch(error=>{console.error(error);process.exitCode=1;});
