const test=require('node:test');
const assert=require('node:assert/strict');
const flow=require('../enchantment-round-core.js');
function step(fn,...args){const r=fn(...args);assert.equal(r.ok,true,r.reason);return r.state;}
test('referee begins; each player reveals only their own assigned card; scoring opens after both',()=>{
  let s=flow.create('M1','user-a','user-b');
  assert.equal(flow.start(s,false).reason,'referee-required');
  s=step(flow.start,s,true);
  s=step(flow.assign,s,1,'A','double_burst');s=step(flow.assign,s,1,'B','weaken_spin');
  assert.equal(flow.view(s,'A').cards.A,null);
  assert.equal(flow.reveal(s,1,'A','user-b').reason,'player-required');
  s=step(flow.reveal,s,1,'A','user-a');
  assert.equal(flow.view(s,'A').cards.B,null);
  assert.equal(flow.view(s,'A').cards.A,'double_burst');
  assert.equal(flow.submit(s,1,'A','burst',true).reason,'not-ready');
  s=step(flow.reveal,s,1,'B','user-b');
  assert.equal(flow.view(s,'referee').cards.B,'weaken_spin');
  const r=flow.submit(s,1,'A','burst',true);assert.equal(r.event.points,4);
  assert.equal(r.state.phase,'awaiting-result');assert.equal(r.state.scores.A,4);
  assert.equal(flow.confirm(r.state,false).reason,'referee-required');
  assert.equal(step(flow.confirm,r.state,true).phase,'completed');
  const undone=step(flow.undo,r.state,true);
  assert.equal(undone.phase,'ready-to-score');assert.equal(undone.scores.A,0);
  assert.deepEqual(undone.cards,{A:'double_burst',B:'weaken_spin'});
});
test('round token and assignment prevent rerolls and duplicate scoring',()=>{
  let s=step(flow.start,flow.create('M2','a','b'),true);
  assert.equal(flow.assign(s,1,'A','boost_spin').reason,'invalid-card');
  s=step(flow.assign,s,1,'A','double_spin');
  assert.equal(flow.assign(s,1,'A','double_burst').reason,'already-assigned');
  s=step(flow.assign,s,1,'B','weaken_burst');
  s=step(flow.reveal,s,1,'A','a');
  assert.equal(flow.reveal(s,1,'A','a').idempotent,true);
  s=step(flow.reveal,s,1,'B','b');
  assert.equal(flow.submit(s,1,'A','spin',false).reason,'referee-required');
  s=step(flow.submit,s,1,'A','spin',true);
  assert.equal(s.round,2);assert.equal(s.phase,'drawing');
  assert.equal(flow.submit(s,1,'A','spin',true).reason,'not-ready');
  assert.equal(flow.reveal(s,1,'A','a').reason,'stale-round');
  assert.deepEqual(s.cards,{A:null,B:null});
  s=step(flow.undo,s,true);
  assert.equal(s.round,1);assert.equal(s.phase,'ready-to-score');
  assert.equal(s.scores.A,0);assert.equal(s.cards.A,'double_spin');
});
test('two triggering cards award defense points and advance the round',()=>{
  let s=step(flow.start,flow.create('M3','a','b'),true);
  s=step(flow.assign,s,1,'A','double_burst');s=step(flow.assign,s,1,'B','weaken_burst');
  s=step(flow.reveal,s,1,'A','a');s=step(flow.reveal,s,1,'B','b');
  const r=flow.submit(s,1,'A','burst',true);
  assert.equal(r.ok,true);assert.equal(r.event.points,1);
  assert.equal(r.event.appliedCardId,'weaken_burst');
  assert.equal(r.state.scores.A,1);assert.equal(r.state.round,2);
});
test('two faults award a fixed point unaffected by either drawn card',()=>{
  let s=step(flow.start,flow.create('MF','a','b'),true);
  s=step(flow.assign,s,1,'A','double_spin');
  s=step(flow.assign,s,1,'B','weaken_spin');
  s=step(flow.reveal,s,1,'A','a');s=step(flow.reveal,s,1,'B','b');
  assert.equal(flow.fault(s,1,'B',false).reason,'referee-required');
  s=step(flow.fault,s,1,'B',true);
  assert.equal(s.faults.B,1);assert.equal(s.scores.A,0);
  const second=flow.fault(s,1,'B',true);
  assert.equal(second.event.type,'fault');assert.equal(second.event.points,1);
  assert.equal(second.event.appliedCardId,null);assert.equal(second.state.scores.A,1);
  assert.equal(second.state.round,2);
  const restored=step(flow.undo,second.state,true);
  assert.equal(restored.round,1);assert.equal(restored.scores.A,0);
  assert.equal(restored.faults.B,1);
  const erased=flow.undo(restored,true);
  assert.equal(erased.warningUndone.offender,'B');assert.equal(erased.state.faults.B,0);
});
test('a normal scoring event ends the round and restores prior warning on undo',()=>{
  let s=step(flow.start,flow.create('MW','a','b'),true);
  s=step(flow.assign,s,1,'A','seal');s=step(flow.assign,s,1,'B','weaken_burst');
  s=step(flow.reveal,s,1,'A','a');s=step(flow.reveal,s,1,'B','b');
  s=step(flow.fault,s,1,'A',true);
  const r=flow.submit(s,1,'A','spin',true);
  assert.equal(r.state.faults.A,0);assert.equal(r.state.round,2);
  const restored=step(flow.undo,r.state,true);
  assert.equal(restored.faults.A,1);assert.equal(restored.round,1);
});
