'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const root=require('node:path').join(__dirname,'..');
const source=fs.readFileSync(require('node:path').join(root,'modules','main-app','hunter-utils.js'),'utf8');
const core=fs.readFileSync(require('node:path').join(root,'modules','main-app','core.js'),'utf8');
const css=fs.readFileSync(require('node:path').join(root,'modules','main-css','player-center-hunter.css'),'utf8');
const start=source.indexOf('function hunterSeniorityBonus(level){');
const end=source.indexOf('Object.assign(window.BXHHunterUtils',start);
assert(start>=0&&end>start,'license grade calculation exists in hunter-utils');
const context=vm.createContext({window:{}});
vm.runInContext(source.slice(start,end),context);
const bonus=level=>vm.runInContext(`hunterSeniorityBonus(${level})`,context);
const grade=(analysis,level)=>{context.analysis=analysis;context.level=level;return vm.runInContext('hunterLicenseGrade(analysis,level)',context)};
assert.equal(bonus(1),0);
assert.equal(bonus(99),15);
for(let level=2;level<=99;level++)assert(bonus(level)>bonus(level-1),`LV.${level} gains seniority`);
assert.equal(bonus(4).toFixed(1),'1.1');
assert.equal(grade({eligible:false,overall:null},99).label,'評級中');
assert.equal(grade({eligible:false,overall:null},99).tier,'pending');
const blackDad=grade({eligible:true,overall:54,matches:17,validRounds:39},4);
assert.equal(blackDad.label,'C 級獵人');
assert.equal(blackDad.tier,'c');
assert.equal(blackDad.score.toFixed(1),'55.1');
assert.equal(grade({eligible:true,overall:49,matches:100,validRounds:300},99).label,'C 級獵人');
assert.equal(grade({eligible:true,overall:55,matches:9,validRounds:50},99).label,'C 級獵人');
assert.equal(grade({eligible:true,overall:65,matches:20,validRounds:60},99).label,'S 級獵人');
assert.equal(grade({eligible:true,overall:65,matches:20,validRounds:60},99).tier,'s');
assert.equal(grade({eligible:true,overall:75,matches:40,validRounds:120},99).label,'國家級獵人');
assert.equal(grade({eligible:true,overall:75,matches:40,validRounds:120},99).tier,'national');
assert.equal(grade({eligible:true,overall:74.9,matches:40,validRounds:120},99).label,'S 級獵人');
assert.equal(grade({eligible:true,overall:75,matches:39,validRounds:120},99).label,'S 級獵人');
assert.equal(grade({eligible:true,overall:75,matches:40,validRounds:119},99).label,'S 級獵人');
assert.equal(grade({eligible:true,overall:75,matches:40,validRounds:120},1).label,'S 級獵人');
assert.equal(grade({eligible:true,overall:100,matches:100,validRounds:300},99).label,'國家級獵人');
assert.equal(grade({eligible:true,overall:100,matches:100,validRounds:300},99).score,100);
for(const tier of ['e','d','c','a','s','national'])assert(css.includes('.hunter-grade-badge.grade-'+tier+'{'),tier+' badge style missing');
assert(core.includes('hunter-grade-badge grade-\'+licenseGrade.tier'), 'badge must use calculated tier');
console.log('PASS hunter license grade, bonus progression and high-rank gates');
