const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),cp=require('child_process'),os=require('os'),path=require('path');
const core=fs.readFileSync('modules/main-app/core.js','utf8');
function setup(){const c=vm.createContext({window:{},console});for(const f of ['domain-utils','hunter-utils'])vm.runInContext(fs.readFileSync('modules/main-app/'+f+'.js','utf8'),c);Object.assign(c,c.window.BXHHunterUtils,{HUNTER_ANALYSIS_TYPES:['extreme','knockout','burst','spin'],HUNTER_ANALYSIS_LABELS:{extreme:'極限',knockout:'擊飛',burst:'爆裂',spin:'轉停'},HUNTER_ANALYSIS_MIN_MATCHES:3,HUNTER_ANALYSIS_MIN_ROUNDS:8,esc:String});for(const name of ['hunterBuildAnalysis','hunterStrengthDiagnosticsHtml']){const a=core.indexOf('function '+name+'('),b=core.indexOf('\nfunction ',a+1);vm.runInContext(core.slice(a,b),c);}return c;}
const record=i=>({eventCode:'B5',matchId:'m'+i,completedAt:200+i,matchStartedAt:100+i,scoringVersion:'bxh-4pt-v1',analyzable:true,isWin:true,opponent:{playerId:'P'+i},scoreFor:4,scoreAgainst:1,roundsPerspective:[{type:'burst',points:2,perspective:'for'},{type:'knockout',points:2,perspective:'for'},{type:'spin',points:1,perspective:'against'}]});
const records=n=>Array.from({length:n},(_,i)=>record(i+1));
const rating=(r,opponent=1000)=>({...r,ratingSnapshot:{source:'server',verified:true,version:'fixture-rating-v1',capturedAt:50,selfBefore:1000,opponentBefore:opponent}});
test('small unbeaten samples have wider uncertainty than large samples; no data is distinct',()=>{const c=setup(),small=c.hunterWinRateInterval(3,3),large=c.hunterWinRateInterval(100,100);assert.ok(small.high-small.low>large.high-large.low);assert.ok(small.low<50);assert.ok(large.low>95);assert.equal(c.hunterWinRateInterval(0,0),null);assert.equal(c.hunterWinRateInterval(4,3),null);});
test('repeat-opponent diagnostics use stable IDs and same known subset without name joins',()=>{const c=setup(),rows=records(10).map((r,i)=>({...r,isWin:i<8,opponent:{playerId:i<8?'weak':'strong'}})),d=c.hunterStrengthDiagnostics(rows);assert.equal(d.uniqueOpponents,2);assert.equal(d.repeated,8);assert.equal(d.largestShare,80);assert.equal(d.knownWinRate,80);assert.equal(d.opponentBalancedWinRate,50);delete rows[0].opponent.playerId;rows[0].opponent.name='weak';assert.equal(c.hunterStrengthDiagnostics(rows).unresolved,1);});
test('pre-match rating rejects post-start, unverified, missing and nonfinite snapshots',()=>{const c=setup(),r=rating(record(1));assert.ok(c.hunterPreMatchRating(r));for(const patch of [{capturedAt:101},{capturedAt:102},{verified:false},{source:'current-profile'},{opponentBefore:NaN},{selfBefore:null}])assert.equal(c.hunterPreMatchRating({...r,ratingSnapshot:{...r.ratingSnapshot,...patch}}),null);assert.equal(c.hunterPreMatchRating(record(1)),null);});
test('no default new formula; missing data and cross-version snapshots block candidate evaluation',()=>{const c=setup(),rows=records(4),candidate={version:'fixture-only',evaluate:()=>{throw Error('must not evaluate')}};assert.equal(c.hunterBacktestStrength(rows,c.hunterBuildAnalysis).candidateReason,'no-calibrated-formula');assert.equal(c.hunterBacktestStrength(rows,c.hunterBuildAnalysis,candidate).candidateReason,'missing-pre-match-ratings');const rated=rows.map(r=>rating(r));rated[0].ratingSnapshot.version='other';assert.equal(c.hunterBacktestStrength(rated,c.hunterBuildAnalysis,candidate).candidateReason,'mixed-rating-versions');rated[0].completedAt=0;delete rated[0].eventDate;const undated=c.hunterBacktestStrength(rated,c.hunterBuildAnalysis,candidate);assert.equal(undated.candidateReason,'undated');assert.equal(undated.maxBaselineJump,null);assert.ok(undated.history.every(r=>r.baselineJump===null));});
test('parallel replay evaluates chronological prefixes only, suppresses tiny samples and measures jumps',()=>{const c=setup(),rows=records(5).map(r=>rating(r)),candidate={version:'fixture-contract-only',evaluate:prefix=>prefix.length*10};const report=c.hunterBacktestStrength(rows.slice().reverse(),c.hunterBuildAnalysis,candidate);assert.equal(report.history[0].candidateScore,null);assert.equal(report.history[1].baselineScore,null);assert.equal(report.history[2].candidateScore,30);assert.equal(report.history[4].candidateScore,50);assert.equal(report.maxCandidateJump,10);assert.equal(report.maxBaselineJump,0);assert.equal(report.history[0].matchKey,'B5|m1');assert.equal(c.hunterBuildAnalysis(rows).overall,92);});
test('synthetic hook distinguishes strong/weak opponents without activating official scoring',()=>{const c=setup(),candidate={version:'synthetic-acceptance-hook',evaluate:prefix=>50+(prefix.reduce((s,r)=>s+r.rating.opponent-r.rating.self,0)/prefix.length)/10};const strong=records(3).map(r=>rating(r,1200)),weak=records(3).map(r=>rating(r,800));assert.equal(c.hunterBuildAnalysis(strong).overall,c.hunterBuildAnalysis(weak).overall);assert.ok(c.hunterBacktestStrength(strong,c.hunterBuildAnalysis,candidate).history[2].candidateScore>c.hunterBacktestStrength(weak,c.hunterBuildAnalysis,candidate).history[2].candidateScore);assert.throws(()=>c.hunterBacktestStrength(strong,c.hunterBuildAnalysis,{version:'bad',evaluate:()=>101}),/within/);});
test('diagnostics respect corrected/revoked and trusted standard-only records; partial UI pauses conclusions',()=>{const c=setup(),r=record(1),revoked={...r,completed:false,updatedAt:999};assert.equal(c.hunterStrengthDiagnostics([r,revoked]).matches,0);assert.equal(c.hunterStrengthDiagnostics([{...r,scoringVersion:'bxh-enchantment-v2'}]).matches,0);assert.equal(c.hunterStrengthDiagnostics([{...r,scoreFor:99}]).matches,0);const html=c.hunterStrengthDiagnosticsHtml(records(3),true);assert.match(html,/暫停回測結論/);assert.match(html,/不代表實力分的信賴區間/);assert.match(html,/不能以目前評等回填/);assert.match(html,/候選實力分<\/div><div class="value small">—/);});
test('offline replay output omits opponent identities, event keys, snapshots and raw rounds',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hunter-b5-'));try{const input=path.join(dir,'records.json');fs.writeFileSync(input,JSON.stringify(records(4)));const r=cp.spawnSync(process.execPath,['scripts/backtest-hunter-strength.cjs','--input',input],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const report=JSON.parse(r.stdout);assert.equal(report.officialScoreChanged,false);assert.equal(report.history.length,4);assert.equal(report.history[2].baselineScore,92);for(const text of ['playerId','matchKey','roundsPerspective','ratingSnapshot'])assert.equal(r.stdout.includes(text),false);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
