'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'..','index.html'),'utf8');
const start=source.indexOf('function hunterSeniorityBonus(level){');
const end=source.indexOf('function hunterPeriodSummary(period){',start);
assert(start>=0&&end>start,'license grade calculation exists');
const context=vm.createContext({});
vm.runInContext(source.slice(start,end),context);
const bonus=level=>vm.runInContext(`hunterSeniorityBonus(${level})`,context);
const grade=(analysis,level)=>{context.analysis=analysis;context.level=level;return vm.runInContext('hunterLicenseGrade(analysis,level)',context)};
assert.equal(bonus(1),0);
assert.equal(bonus(99),15);
for(let level=2;level<=99;level++)assert(bonus(level)>bonus(level-1),`LV.${level} gains seniority`);
assert.equal(bonus(4).toFixed(1),'1.1');
assert.equal(grade({eligible:false,overall:null},99).label,'評級中');
const blackDad=grade({eligible:true,overall:54,matches:17,validRounds:39},4);
assert.equal(blackDad.label,'C 級獵人');
assert.equal(blackDad.score.toFixed(1),'55.1');
assert.equal(grade({eligible:true,overall:49,matches:100,validRounds:300},99).label,'C 級獵人');
assert.equal(grade({eligible:true,overall:55,matches:9,validRounds:50},99).label,'C 級獵人');
assert.equal(grade({eligible:true,overall:65,matches:20,validRounds:60},99).label,'S 級獵人');
assert.equal(grade({eligible:true,overall:100,matches:100,validRounds:300},99).label,'S 級獵人');
assert.equal(grade({eligible:true,overall:100,matches:100,validRounds:300},99).score,100);
console.log('PASS hunter license grade, bonus progression and high-rank gates');
