'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../modules/main-app/core.js'),'utf8');
const cloud=fs.readFileSync(path.join(__dirname,'../modules/cloud/cloud-runtime.js'),'utf8');
const publicWatchPatch=fs.readFileSync(path.join(__dirname,'../modules/main-app/public-watch-isolation.js'),'utf8');

assert(source.includes('雙命守擂計分板｜'));
assert(source.includes("'●'.repeat(life)+'○'.repeat(Math.max(0,2-life))"));
assert(source.includes("if(view.revealed&&state.startedAt){"));
assert(!source.includes("if(view.revealed&&state.startedAt&&view.isReferee===true){"));
assert(source.includes("'lineups-incomplete':'雙方尚未完成排陣"));
assert(source.includes('data-action="team-score-direct"'));
assert(source.includes('data-action="team-lineup-default"'));
assert(source.includes("action:'default',code,matchId,teamId:team.id"));
assert(source.includes("view?.defaulted?.[t.id]"));
assert(source.includes("'lineup-already-submitted':'該隊已提交排陣"));
assert(source.includes('data-winner-side="'));
assert(source.includes("[['spin','轉停'],['burst','爆裂'],['over','擊飛'],['extreme','極限']]"));
assert(!source.includes('id="team-score-winner-'));
assert(source.includes('function renderTeamReferee()'));
assert(source.includes('if(mine&&!refereeMode){'));
assert(publicWatchPatch.includes("if(publicWatchReturnContext&&mode!=='referee')return '';"));
assert(publicWatchPatch.includes('return originalLineupPanel(m,mode);'));
assert(publicWatchPatch.includes("activeTab==='referee'&&!publicWatchReturnContext"));
assert(publicWatchPatch.includes("const allowedTabs=new Set(['ladder','live','bracket'])"));
assert(publicWatchPatch.includes("v2.dataset.visibleTabs='ladder,live,bracket'"));
assert(publicWatchPatch.includes("node.textContent='目前為公開觀賽模式'"));
assert(source.includes("if(state.meta?.battleMode===\"team\")return renderTeamReferee();"));
assert(source.includes('data-action="set-team-bracket-view"'));
assert(source.includes("teamBracketViewMode==='live'?renderTeamMatchList(false):renderTeamTree()"));
assert(source.includes('function renderTeamTree()'));
assert(cloud.includes('subscribeTeamLive(code, callback)'));
console.log('PASS team scoring board initial-state and error-message UI contracts');
