const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const core=fs.readFileSync('modules/main-app/core.js','utf8');
const start=core.indexOf('const BXH_INTERFACE_THEME_KEY=');
const end=core.indexOf('function accountMenuItemsHtml()',start);
const stored=new Map();
const root={value:'gold',getAttribute(){return this.value},setAttribute(k,v){this.value=v}};
const context={firebaseUser:null,userProfile:null,document:{documentElement:root},localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v),removeItem:k=>stored.delete(k)},esc:s=>s,window:{cloudAuth:{saveInterfaceTheme:async()=>({ok:true})}},showToast(){throw Error('save failed')}};
vm.createContext(context);vm.runInContext(core.slice(start,end),context);
context.firebaseUser={uid:'A'};context.userProfile={role:'staff',active:true};
context.restoreAccountInterfaceTheme('A',context.userProfile);
context.applyInterfaceTheme('clow');
assert.equal(root.value,'clow');assert.equal(stored.get('bxh.interface.theme.account.v1.A'),'clow');
assert.match(context.themePickerHtml(),/庫洛魔法使/);
context.firebaseUser=null;context.userProfile=null;context.syncInterfaceThemeVisibility();assert.equal(root.value,'clow');
context.firebaseUser={uid:'B'};context.userProfile={role:'staff',active:true};context.restoreAccountInterfaceTheme('B',context.userProfile);assert.equal(root.value,'gold');
context.restoreAccountInterfaceTheme('A',{role:'staff',active:true});assert.equal(root.value,'clow');
context.applyInterfaceTheme('three-gods');assert.equal(root.value,'three-gods');context.applyInterfaceTheme('gold');assert.equal(root.value,'gold');
context.userProfile={role:'player',active:true};context.applyInterfaceTheme('clow');assert.equal(root.value,'gold');assert.doesNotMatch(context.themePickerHtml(),/庫洛魔法使/);
context.userProfile={role:'staff',active:false};context.applyInterfaceTheme('clow');assert.equal(root.value,'gold');
const early=fs.readFileSync('index.html','utf8').match(/<script>\s*(\(function\(\)\{[\s\S]*?data-bxh-theme[\s\S]*?\}\)\(\);)\s*<\/script>/)[1];
vm.runInNewContext(early,{document:{documentElement:root},localStorage:{getItem:k=>({'bxh.interface.theme.entrance.uid.v1':'A','bxh.interface.theme.account.v1.A':'clow'})[k]}});assert.equal(root.value,'clow');
const css=fs.readFileSync('modules/theme-clow/styles.css','utf8');
assert.match(css,/content:"櫻"/);assert.match(css,/content:"狼"/);assert.match(css,/content:"知"/);
for(const name of ['小櫻','小狼','知世'])assert.match(core,RegExp('<span class="clow-character-name">'+name+'</span>'));
assert.match(css,/entrance-battle-atlas\.webp/);
assert.ok(fs.statSync('assets/clow/entrance-battle-atlas.webp').size>100000);
assert.match(css,/prefers-reduced-motion/);
for(const path of ['modules/main-app/core.js','modules/main-app/community-host.js'])assert.match(fs.readFileSync(path,'utf8'),/clow-seal-layer/);
console.log('PASS Clow account isolation, first paint, role eligibility, art and header');
