const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const core=fs.readFileSync('modules/main-app/core.js','utf8');
const start=core.indexOf('const BXH_INTERFACE_THEME_KEY=');
const end=core.indexOf('function accountMenuItemsHtml()',start);
const stored=new Map();
const root={value:'gold',getAttribute(){return this.value},setAttribute(k,v){this.value=v}};
const context={firebaseUser:null,userProfile:null,document:{documentElement:root},localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v),removeItem:k=>stored.delete(k)},esc:s=>s,window:{cloudAuth:{saveInterfaceTheme:async()=>({ok:true})}},showToast(){throw Error('save failed')}};
vm.createContext(context);vm.runInContext(core.slice(start,end),context);
context.firebaseUser={uid:'A'};context.userProfile={role:'staff',active:true};
context.restoreAccountInterfaceTheme('A',context.userProfile);
context.applyInterfaceTheme('three-gods');
assert.equal(root.value,'three-gods');assert.equal(stored.get('bxh.interface.theme.account.v1.A'),'three-gods');
assert.match(context.themePickerHtml(),/三幻神/);
context.firebaseUser=null;context.userProfile=null;context.syncInterfaceThemeVisibility();assert.equal(root.value,'three-gods');
context.firebaseUser={uid:'B'};context.userProfile={role:'staff',active:true};context.restoreAccountInterfaceTheme('B',context.userProfile);assert.equal(root.value,'gold');
context.restoreAccountInterfaceTheme('A',{role:'staff',active:true});assert.equal(root.value,'three-gods');
context.applyInterfaceTheme('directive');assert.equal(root.value,'directive');context.applyInterfaceTheme('gold');assert.equal(root.value,'gold');
context.userProfile={role:'player',active:true};context.applyInterfaceTheme('three-gods');assert.equal(root.value,'gold');assert.doesNotMatch(context.themePickerHtml(),/三幻神/);
context.userProfile={role:'staff',active:false};context.applyInterfaceTheme('three-gods');assert.equal(root.value,'gold');
const early=fs.readFileSync('index.html','utf8').match(/<script>\s*(\(function\(\)\{[\s\S]*?data-bxh-theme[\s\S]*?\}\)\(\);)\s*<\/script>/)[1];
vm.runInNewContext(early,{document:{documentElement:root},localStorage:{getItem:k=>({'bxh.interface.theme.entrance.uid.v1':'A','bxh.interface.theme.account.v1.A':'three-gods'})[k]}});assert.equal(root.value,'three-gods');
console.log('PASS 三幻神 account isolation, first paint, role eligibility and theme switching');
