const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const core=fs.readFileSync('modules/main-app/core.js','utf8');
const start=core.indexOf('const BXH_INTERFACE_THEME_KEY=');
const end=core.indexOf('function accountMenuItemsHtml()',start);
const stored=new Map();
const root={value:'gold',getAttribute(){return this.value},setAttribute(k,v){this.value=v}};
const context={firebaseUser:null,userProfile:null,document:{documentElement:root},localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v),removeItem:k=>stored.delete(k)},esc:s=>s,window:{cloudAuth:{saveInterfaceTheme:async()=>({ok:true})}},showToast(){throw Error('save failed')}};
vm.createContext(context);vm.runInContext(core.slice(start,end),context);
context.firebaseUser={uid:'A'};context.userProfile={role:'staff',active:true};
context.restoreAccountInterfaceTheme('A',context.userProfile);
context.applyInterfaceTheme('gundam');
assert.equal(root.value,'gundam');assert.equal(stored.get('bxh.interface.theme.account.v1.A'),'gundam');
assert.match(context.themePickerHtml(),/鋼彈/);
context.firebaseUser=null;context.userProfile=null;context.syncInterfaceThemeVisibility();assert.equal(root.value,'gundam');
context.firebaseUser={uid:'B'};context.userProfile={role:'staff',active:true};context.restoreAccountInterfaceTheme('B',context.userProfile);assert.equal(root.value,'gold');
context.restoreAccountInterfaceTheme('A',{role:'staff',active:true});assert.equal(root.value,'gundam');
context.applyInterfaceTheme('three-gods');assert.equal(root.value,'three-gods');context.applyInterfaceTheme('gold');assert.equal(root.value,'gold');
context.userProfile={role:'player',active:true};context.applyInterfaceTheme('gundam');assert.equal(root.value,'gold');assert.doesNotMatch(context.themePickerHtml(),/鋼彈/);
context.userProfile={role:'staff',active:false};context.applyInterfaceTheme('gundam');assert.equal(root.value,'gold');
const early=fs.readFileSync('index.html','utf8').match(/<script>\s*(\(function\(\)\{[\s\S]*?data-bxh-theme[\s\S]*?\}\)\(\);)\s*<\/script>/)[1];
vm.runInNewContext(early,{document:{documentElement:root},localStorage:{getItem:k=>({'bxh.interface.theme.entrance.uid.v1':'A','bxh.interface.theme.account.v1.A':'gundam'})[k]}});assert.equal(root.value,'gundam');
const css=fs.readFileSync('modules/theme-gundam/styles.css','utf8');
assert.match(css,/entrance\.webp/);
assert.match(css,/haro-header\.webp/);
assert.match(css,/pointer-events:none/);
assert.match(css,/role-card-player\{top:17%/);
assert.match(css,/role-card-admin\{top:41.5%/);
assert.match(css,/role-card-guest\{top:66.3%/);
for(const path of ['modules/main-app/core.js','modules/main-app/community-host.js'])assert.match(fs.readFileSync(path,'utf8'),/gundam-haro-layer/);
for(const path of ['assets/gundam/entrance.webp','assets/gundam/haro-header.webp'])assert.ok(fs.statSync(path).size>10000);
console.log('PASS Gundam account isolation, eligibility, approved entrance mapping and Haro header');
