'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.join(__dirname, '..');
const core = fs.readFileSync(path.join(root, 'modules', 'main-app', 'core.js'), 'utf8');
const ladder = fs.readFileSync(path.join(root, 'ladder-secondary-ui.js'), 'utf8');
assert(core.includes("'對戰召集人':'assets/title-rare-host-3.webp'"), 'Host-3 catalog artwork mapping missing');
assert(ladder.includes('"對戰召集人":"assets/title-rare-host-3.webp"'), 'Host-3 ladder artwork mapping missing');
const png = fs.readFileSync(path.join(root, 'assets/title-rare-host-3.png'));
assert.equal(crypto.createHash('sha256').update(png).digest('hex'), 'f25be44b04c7b99851e22a824154b380221c6652868a34d1e16201030536247b', 'PNG must be the exact user-approved original');
assert.equal(png.subarray(1, 4).toString(), 'PNG');
assert.equal(png.readUInt32BE(16), 2172);
assert.equal(png.readUInt32BE(20), 724);
assert.equal(png[25], 6, 'PNG must retain RGBA transparency');
const webp = fs.readFileSync(path.join(root, 'assets/title-rare-host-3.webp'));
assert.equal(webp.subarray(0, 4).toString(), 'RIFF');
assert.equal(webp.subarray(8, 12).toString(), 'WEBP');
assert.equal(webp.readUInt32LE(4) + 8, webp.length, 'WebP container is truncated');
assert(webp.length > 1000 && webp.length < 1000000, 'WebP image size outside expected budget');
console.log('PASS host-3 original artwork, transparency metadata, catalog and ladder mapping');
