'use strict';
// Pure regressions against production inline functions; no network/Firebase writes.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=process.argv[2]||path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ctx=vm.createContext({URL,console});
vm.runInContext('const EVENT_INFO_SCHEMA_VERSION="bxh.event-info.v2"; let state={};',ctx);
const names=['emptyEventInfoV2','splitLegacyVenueText','buildLegacyVenueText','normalizeGoogleMapsUrl','extractGoogleMapsUrlsFromText','extractGoogleMapsUrlFromText','googleMapsNavigationUrl','appleMapsNavigationUrl','normalizeEventInfoV2','venueForEventState','syncEventInfoV2FromLegacy','applyVenueDraftToState','publicVenueFromTournament','buildPublicEventInfo','renderVenueNavigationMenu'];
for(const name of names){const start=html.indexOf('function '+name+'('),end=html.indexOf('\n}',start)+2;assert(start>=0&&end>start,'Missing function '+name);vm.runInContext(html.slice(start,end),ctx,{filename:name+'.js'});}
const api=vm.runInContext('({'+names.join(',')+'})',ctx);
let count=0;const test=(label,fn)=>{fn();count++;console.log('PASS '+label);};
const link='https://maps.app.goo.gl/WjCbzZuuCuWHfrix9',address='台南市南區健康路二段386號';
const baseVenue={name:'北京麻辣鍋',address,googleMapsUrl:link,navigationEnabled:true};
const makeState=()=>({meta:{name:'測試',location:'北京麻辣鍋｜'+address},eventInfo:{venue:{...baseVenue,legacyText:'北京麻辣鍋｜'+address}},matches:[{id:'m',scoreA:2}],players:[{id:'p'}]});
for(const url of [link,'https://maps.app.goo.gl/2C49QmstjiqpyUfu7','https://maps.google.com/?q='+encodeURIComponent(address),'https://www.google.com/maps?cid=1','https://www.google.com.tw/maps/place/test'])test('Accept supported Maps URL '+url.slice(0,55),()=>assert.equal(api.normalizeGoogleMapsUrl(url),new URL(url).href));
for(const url of ['javascript:alert(1)','http://maps.app.goo.gl/a','https://maps.app.goo.gl.evil.test/a','https://www.google.com/maps-malware','https://www.google.com/url?q=https://evil.test','https://user:pass@maps.app.goo.gl/a','https://maps.app.goo.gl:444/a','https://maps.app.goo.gl/','https://maps.app.goo.gl/WjCbz…','https://maps.app.goo.gl/a\nb','https://maps.app.goo.gl/a%0ab','https://evil.test/maps','https://www.google.com/maps/'+('a'.repeat(2048))])test('Reject unsafe/invalid Maps URL '+url.slice(0,70),()=>assert.equal(api.normalizeGoogleMapsUrl(url),''));
test('Markdown link uses actual full target',()=>assert.equal(api.extractGoogleMapsUrlFromText('[maps.app.goo.gl/WjCbz…]('+link+')'),link));
test('Trailing Chinese punctuation',()=>assert.equal(api.extractGoogleMapsUrlFromText('地圖：'+link+'。'),link));
test('Google query without trailing path slash',()=>assert.equal(api.extractGoogleMapsUrlFromText('https://www.google.com/maps?cid=1'),'https://www.google.com/maps?cid=1'));
test('Duplicate link is one candidate',()=>assert.equal(api.extractGoogleMapsUrlFromText(link+' '+link),link));
test('Conflicting links do not silently select first',()=>assert.equal(api.extractGoogleMapsUrlFromText(link+' https://maps.app.goo.gl/another'),''));
test('Never fetch short links or use location in pure navigation helpers',()=>{for(const name of ['normalizeGoogleMapsUrl','extractGoogleMapsUrlsFromText','googleMapsNavigationUrl','appleMapsNavigationUrl'])assert(!/\bfetch\(|geolocation/.test(api[name].toString()));});
test('Google preserves host-provided URL',()=>assert.equal(api.googleMapsNavigationUrl(baseVenue),link));
test('Google fallback encodes address and no fixed origin',()=>{const u=new URL(api.googleMapsNavigationUrl({address}));assert.equal(u.searchParams.get('api'),'1');assert.equal(u.searchParams.get('destination'),address);assert(!u.searchParams.has('origin'));});
test('Apple destination is address, not Google short link',()=>{const u=new URL(api.appleMapsNavigationUrl(baseVenue));assert.equal(u.hostname,'maps.apple.com');assert.equal(u.searchParams.get('daddr'),address);});
test('Name-only destinations not guessed',()=>{assert.equal(api.googleMapsNavigationUrl({name:'星巴克'}),'');assert.equal(api.appleMapsNavigationUrl({name:'星巴克'}),'');});
test('Map-only permits Google but not invented Apple location',()=>{assert.equal(api.googleMapsNavigationUrl({googleMapsUrl:link}),link);assert.equal(api.appleMapsNavigationUrl({googleMapsUrl:link}),'');});
test('Cleared venue never revives fallback text',()=>{const s=makeState();api.applyVenueDraftToState({venueName:'',venueAddress:'',googleMapsUrl:'',navigationEnabled:true,location:s.meta.location},s);assert.equal(s.meta.location,'');assert.equal(s.eventInfo.venue.name,'');assert.equal(s.eventInfo.venue.address,'');assert.equal(s.eventInfo.venue.navigationEnabled,false);});
test('Address-only survives normal persistence',()=>{const s=makeState();api.applyVenueDraftToState({venueName:'',venueAddress:address,googleMapsUrl:link,navigationEnabled:true},s);api.syncEventInfoV2FromLegacy(s);assert.equal(s.eventInfo.venue.name,'');assert.equal(s.eventInfo.venue.address,address);assert.equal(s.eventInfo.venue.googleMapsUrl,link);});
test('Legacy-only form remains readable',()=>{const s=makeState();api.applyVenueDraftToState({location:'新店家｜新地址'},s);assert.equal(s.meta.location,'新店家｜新地址');assert.equal(s.eventInfo.venue.name,'新店家');});
test('Changed legacy venue clears stale navigation link',()=>{const s=makeState();s.meta.location='另一間店｜另一個地址';api.syncEventInfoV2FromLegacy(s);assert.equal(s.eventInfo.venue.googleMapsUrl,'');assert.equal(s.eventInfo.venue.navigationEnabled,false);assert.equal(s.eventInfo.venue.name,'另一間店');});
test('Clearing legacy location clears old structured venue',()=>{const s=makeState();s.meta.location='';api.syncEventInfoV2FromLegacy(s);assert.equal(s.eventInfo.venue.address,'');assert.equal(s.eventInfo.venue.googleMapsUrl,'');});
test('Stable structured venue retains all navigation values',()=>{const s=makeState();api.syncEventInfoV2FromLegacy(s);assert.equal(s.eventInfo.venue.googleMapsUrl,link);assert.equal(s.eventInfo.venue.address,address);});
test('Public projection has no source/private fields',()=>{const s=makeState();s.eventInfo.source={originalText:'PRIVATE_ORIGINAL'};s.eventInfo.venue.secret='SECRET';const v=api.buildPublicEventInfo(s);assert.equal(v.venue.googleMapsUrl,link);assert(!JSON.stringify(v).includes('PRIVATE_ORIGINAL'));assert(!JSON.stringify(v).includes('SECRET'));});
test('Public projection does not mutate runtime or matches',()=>{const s=makeState(),before=JSON.stringify(s);api.buildPublicEventInfo(s);assert.equal(JSON.stringify(s),before);});
test('Public legacy mismatch does not keep stale maps',()=>{const v=api.publicVenueFromTournament({location:'別家',parsedData:{eventInfo:{venue:baseVenue}}});assert.equal(v.name,'別家');assert.equal(v.googleMapsUrl,'');});
test('Legacy public room does not silently gain navigation',()=>assert.equal(api.publicVenueFromTournament({location:'北京麻辣鍋｜'+address}).navigationEnabled,false));
test('Navigation off shows no button',()=>assert.equal(api.renderVenueNavigationMenu({...baseVenue,navigationEnabled:false}),''));
test('Navigation is an accessible button, not a clipped nested menu',()=>{const button=api.renderVenueNavigationMenu(baseVenue);assert(button.includes('aria-haspopup="dialog"'));assert(button.includes('data-action="venue-navigation-open"'));assert(!button.includes('<details'));});
test('Copy action and top-layer dialog integrated',()=>{assert(html.includes('data-venue-copy'));assert(html.includes('dialog.showModal()'));assert(html.includes('document.execCommand("copy")===true'));assert(html.includes('if(action==="venue-navigation-open")'));});
test('Form clear is not overwritten by old location',()=>assert(!html.includes('venueAddress:settingsFormDraft.venueAddress,legacyText:settingsFormDraft.location')));
test('Multiple map warning is visible to reviewer',()=>assert(html.includes('原文包含多個地圖連結，未自動選擇')));
console.log('PASS '+count+' P7.12.1 regression cases (no Firebase writes).');
