(function(){
// Core Phase 2E — Player Cards feature module.
// Player search, privacy settings, public card overlay and card actions stay together.
function cardContext(){const uid=currentAuthUid();if(playerCardsUI.uid!==uid)playerCardsUI={uid,query:'',results:null,settings:null,savedSettings:null,editing:false,busy:false,error:'',card:null,opened:false,hasMore:false};return playerCardsUI;}
function playerSearchPanel(){const c=cardContext();return `<details class="panel"><summary style="font-weight:bold;cursor:pointer">尋找玩家</summary><div style="margin-top:14px"><div class="field"><label>玩家名稱或玩家 ID</label><input id="player-card-query" maxlength="60" placeholder="輸入至少 2 個字" value="${esc(c.query)}"></div><button class="btn btn-primary" data-action="card-search" ${c.busy?'disabled':''}>${c.busy?'處理中…':'搜尋'}</button><p class="hint">只搜尋允許被找到的玩家。可輸入部分遊戲名稱或玩家 ID。</p>${c.error?`<p role="status">${esc(c.error)}</p>`:''}${c.results===null?'':c.results.length?c.results.map(p=>`<div class="community-event-card"><button class="btn btn-ghost" data-action="card-open" data-uid="${esc(p.uid)}">${esc(p.name)}${p.title?` ${titleChipHtml(p.title.name,p.title.rarity)}`:''}</button><div class="hint">${esc(p.playerId)}</div></div>`).join(''):'<p>找不到符合條件且允許搜尋的玩家。</p>'}${c.hasMore?'<p class="hint">最多顯示 30 名，請輸入更完整的名稱或 ID。</p>':''}</div></details>`;}
function playerPrivacyPanel(){const c=cardContext(),labels={cardPublic:'公開玩家名片',searchable:'允許被搜尋',showTitle:'公開佩戴稱號（包含天梯）',showAvatar:'公開名片頭像',showPoints:'公開名片積分與階級',showStats:'公開名片勝率與參賽統計'};return `<div class="panel"><div class="panel-title">公開與隱私</div><p class="hint">新功能預設不公開名片、不允許搜尋。名片不含本名、Email、電話、生日。天梯原有排名、名稱及積分仍依排行榜規則顯示；既有賽事頁與頭像不受此設定追溯隱藏。</p>${c.settings&&c.editing?Object.entries(labels).map(([k,v])=>`<label style="display:flex;gap:10px;align-items:center;margin:12px 0"><input type="checkbox" data-card-privacy="${k}" ${c.settings[k]?'checked':''} ${c.busy?'disabled':''}>${v}</label>`).join(''):'<p class="hint">按「編輯公開設定」調整公開項目；儲存成功後會自動收合。</p>'}<div class="btn-row"><button class="btn btn-ghost" data-action="card-settings" ${c.busy?'disabled':''}>編輯公開設定</button>${c.settings&&c.editing?`<button class="btn btn-primary" data-action="card-save" ${c.busy?'disabled':''}>儲存並關閉</button><button class="btn btn-ghost" data-action="card-cancel" ${c.busy?'disabled':''}>取消</button>`:''}<button class="btn btn-ghost" data-action="card-preview" ${c.busy?'disabled':''}>預覽已儲存名片</button></div>${c.error?`<p role="status">${esc(c.error)}</p>`:''}</div>`;}
function renderPlayerCardOverlay(){const c=cardContext();let el=document.getElementById('player-card-overlay');if(!c.opened){el?.remove();return;}if(!el){el=document.createElement('div');el.id='player-card-overlay';document.body.appendChild(el);}el.style.cssText='position:fixed;inset:0;z-index:2200;background:#000b;display:flex;align-items:center;justify-content:center;padding:18px';const p=c.card;el.innerHTML=`<section role="dialog" aria-modal="true" aria-label="玩家名片" class="panel" style="width:100%;max-width:520px;max-height:85dvh;overflow:auto;margin:0"><div class="panel-title">玩家名片</div>${c.busy?'<p>讀取中…</p>':c.error?`<p>${esc(c.error)}</p>`:!p?'<p>此玩家未公開名片，或目前無法查看。</p>':`${p.avatarUrl?`<img src="${esc(p.avatarUrl)}" alt="玩家頭像" style="width:72px;height:72px;border-radius:50%;object-fit:cover">`:''}<h2>${esc(p.name)}</h2><p>${esc(p.playerId)}</p>${p.title?`<p>${titleChipHtml(p.title.name,p.title.rarity)}</p>`:''}${p.points?`<p>${esc(p.points.season)}｜${esc(ladderDisplayTier({...p.points,uid:p.uid}))}</p><p>賽季 ${p.points.seasonPoints} PT · 生涯 ${p.points.careerPoints} PT</p>`:''}${p.stats?`<hr><p>${esc(p.stats.season)} 正式積分賽</p><p>勝率 ${p.stats.winRate===null?'尚無紀錄':p.stats.winRate+'%'}｜${p.stats.wins} 勝 ${p.stats.losses} 敗</p><p>完成 ${p.stats.events} 場｜冠軍 ${p.stats.champion} · 亞軍 ${p.stats.runnerUp} · 季軍 ${p.stats.third} · 殿軍 ${p.stats.fourth}</p><p class="hint">僅計入正常結算且仍有完整對戰資料的本季積分賽；輪空、棄權不計勝敗。${p.stats.incomplete?'部分歷史資料不完整，未納入以上統計。':''}</p>`:''}`}
<button class="btn btn-ghost" data-action="card-close" type="button" style="width:100%;margin-top:14px;min-height:48px">關閉</button></section>`;el.onclick=e=>{if(e.target===el||e.target.closest('[data-action="card-close"]')){e.preventDefault();e.stopPropagation();c.opened=false;renderPlayerCardOverlay();}};}
async function handlePlayerCard(action,button){const c=cardContext();if(c.busy&&action!=='card-close')return;if(action==='card-close'){c.opened=false;renderPlayerCardOverlay();return;}if(!currentAuthUid()&&action!=='card-event-open'){showToast('請先登入以使用玩家搜尋與名片',true);return;}const uid=c.uid;c.error='';if(action==='card-cancel'){c.settings=c.savedSettings?{...c.savedSettings}:null;c.editing=false;c.opened=false;render();return;}let data={};if(action==='card-search'){c.query=document.getElementById('player-card-query')?.value||c.query;data={action:'search',query:c.query};}else if(action==='card-settings')data={action:'settings'};else if(action==='card-save'){data={action:'save',settings:c.settings};}else if(action==='card-open'||action==='card-preview'){data={action:action==='card-preview'?'preview':'card',uid:button?.getAttribute('data-uid')};c.card=null;c.opened=true;}else if(action==='card-event-open'){data={action:'event-card',code:button?.getAttribute('data-code')||'',playerId:button?.getAttribute('data-player-id')||''};c.card=null;c.opened=true;}else return;c.busy=true;render();try{const r=await window.engagementService.playerCard(data);if(uid!==currentAuthUid())return;if(!r?.ok)throw Error('服務未確認完成');if(data.action==='search'){c.results=r.players;c.hasMore=r.hasMore;}if(['settings','save'].includes(data.action)){c.settings={...r.settings};c.savedSettings={...r.settings};c.editing=data.action==='settings';if(data.action==='save'){c.opened=false;c.card=null;showToast('公開設定已儲存');ladderPublicLoaded=false;}}if(['preview','card','event-card'].includes(data.action))c.card=r.card;}catch(e){if(uid===currentAuthUid())c.error=managedFeatureError(e);}finally{if(uid===currentAuthUid()){c.busy=false;render();}}}
function bindPlayerCardInputs(){document.querySelectorAll('[data-card-privacy]').forEach(el=>{el.onchange=()=>{const c=cardContext();if(c.settings){c.settings[el.dataset.cardPrivacy]=el.checked;if(el.dataset.cardPrivacy==='cardPublic'&&!el.checked){c.settings.searchable=false;const b=document.querySelector('[data-card-privacy="searchable"]');if(b)b.checked=false;}}};});const q=document.getElementById('player-card-query');if(q){q.oninput=()=>cardContext().query=q.value;q.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();handlePlayerCard('card-search');}};}}

Object.assign(window.BXHPlayerCardsFeature||(window.BXHPlayerCardsFeature={}),{cardContext,playerSearchPanel,playerPrivacyPanel,renderPlayerCardOverlay,handlePlayerCard,bindPlayerCardInputs});

})();
